service: cyou-shop-server 

provider:
  name: aws
  runtime: nodejs6.10 
  memorySize: 128 
  timeout: 10 
  stage: dev 
  region: us-east-1
functions:
  getStore:
    handler: handler.getStore
    events:
      - http:
          path: store
          method: get
          cors: true
  createStore:
    handler: handler.createStore
    events:
      - http:
          path: store
          method: post
          cors: true
  removeStore:
    handler: handler.removeStore
    events:
      - http:
          path: store
          method: delete
          cors: true
