service: cyou-shop-server 

provider:
  name: aws
  runtime: nodejs6.10 # set node.js runtime
 # memorySize: 128 # set the maximum memory of the Lambdas in Megabytes
 # timeout: 10 # the timeout is 10 seconds (default is 6 seconds)
 # stage: dev # setting the env stage to dev, this will be visible in the routes
 # region: us-east-1
functions:
  getStore:
    handler: handler.getStore
    events:
      - http:
          path: store
          method: get
  createStore:
    handler: handler.createStore
    events:
      - http:
          path: store
          method: post
